<a href="https://colab.research.google.com/github/2303a52351-Saniya/Generative-AI-2025/blob/main/gen_ai_8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Design a multilayer ANN architecture according to the requirements shown below.
Train, test, save (.h5) and deploy the model to predict the quality of wine using the Keras deep
learning library
2. (1 ponto) Calculate training and testing accuracy, build confusion matrix, also calculate recall,
precision and F1-score.
3. (1 ponto) Build the application by loading the saved ANN model.
Tabela 1: ANN Architecture
Layer Neurons Activation Function
Hidden Layer - 1 12 tanh
Hidden Layer - 2 24 tanh
Hidden Layer - 3 30 tanh
Hidden Layer - 4 20 tanh
Hidden Layer - 5 10 tanh
Tabela 2: Training Parameters
epochs batch size error metric Optimizer
200 32 accuracy adam
Dataset: https://drive.google.com/file/d/1uutPAkOSYb2Uror1mk2dZUtoYbCgz6DO/view?
usp=drive_link


In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

data = pd.read_csv('/content/winequality-red.csv')
X, y = data.iloc[:, :-1].to_numpy(), data.iloc[:, -1].to_numpy()

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

def wine_quality_model(input_shape):
    model = Sequential([
        Dense(12, activation='tanh', input_shape=(input_shape,)),
        Dense(24, activation='tanh'),
        Dense(30, activation='tanh'),
        Dense(20, activation='tanh'),
        Dense(10, activation='tanh'),
        Dense(1, activation='sigmoid')
    ])
    return model

model = wine_quality_model(X_train.shape[1])
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train_scaled, y_train, validation_data=(X_val_scaled, y_val), epochs=200, batch_size=32, verbose=1)

model.save("wine_quality_model.h5")

train_loss, train_acc = model.evaluate(X_train_scaled, y_train, verbose=0)
test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)

y_pred = (model.predict(X_test_scaled) > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", report)

loaded_model = tf.keras.models.load_model("wine_quality_model.h5")

new_data = np.array([list(map(float, input().split()))])
new_data_scaled = scaler.transform(new_data)
predicted_result = loaded_model.predict(new_data_scaled)

print("Predicted Wine Quality (0: Bad, 1: Good):", int(predicted_result[0][0] > 0.5))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.0000e+00 - loss: -0.5546 - val_accuracy: 0.0000e+00 - val_loss: -5.3397
Epoch 2/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -7.2162 - val_accuracy: 0.0000e+00 - val_loss: -14.5323
Epoch 3/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -15.7468 - val_accuracy: 0.0000e+00 - val_loss: -19.4762
Epoch 4/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -19.9947 - val_accuracy: 0.0000e+00 - val_loss: -22.7400
Epoch 5/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -22.9312 - val_accuracy: 0.0000e+00 - val_loss: -25.5294
Epoch 6/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -25.5715 - val_accuracy: 0.0000e+00 - val_loss: -28.0917
Epoch 7/200
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -28.2361 - val_accuracy: 0.0000e+00 - val_loss: -30.5344
Epoch 8/200
40/40 ━━━━━━━━━━━

Train Accuracy: 0.0
Test Accuracy: 0.0
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step  
Confusion Matrix:
 [[ 0  0  0  0  0  0]
 [ 6  0  0  0  0  0]
 [66  0  0  0  0  0]
 [66  0  0  0  0  0]
 [19  0  0  0  0  0]
 [ 3  0  0  0  0  0]]
Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       6.0
           5       0.00      0.00      0.00      66.0
           6       0.00      0.00      0.00      66.0
           7       0.00      0.00      0.00      19.0
           8       0.00      0.00      0.00       3.0

    accuracy                           0.00     160.0
   macro avg       0.00      0.00      0.00     160.0
weighted avg       0.00      0.00      0.00     160.0



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

7.0 0.27 0.36 20.7 0.045 45.0 170.0 1.001 3.00 0.45 8.4
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
Predicted Wine Quality (0: Bad, 1: Good): 1
